export const zh = {
  newSession: "新会话",
  untitled: "未命名会话",
  sessions: "会话",
  noSessions: "还没有会话",
  rename: "重命名",
  delete: "删除",
  confirmDelete: "删除这个会话和其中的附图？此操作无法撤销。",
  settings: "设置",
  back: "返回",
  collapse: "折叠面板",
  expand: "展开面板",
  modeSqueeze: "切换为覆盖模式",
  modeOverlay: "切换为挤压模式",
  placeholder: "描述想要的画面或调整…",
  send: "发送",
  stop: "停止",
  attach: "附图",
  latestOutput: "最新出图",
  hint: "Enter 发送 · Shift+Enter 换行",
  thinking: "思考中…",
  thought: (n: number) => `思考 · ${n} 字`,
  requesting: "等待回复…",
  stopped: "已停止",
  interrupted: "已中断",
  retry: "重试",
  copy: "复制",
  copied: "已复制",
  edit: "编辑并重发",
  cancel: "取消",
  save: "保存",
  loadOlder: "加载更早的消息",
  toBottom: "回到底部",
  emptyTitle: "开始写提示词",
  emptyBody: "描述你想要的画面，或附一张图让我分析。我能读写提示词和全部生成参数，但出图要你自己点 Generate。",
  noProfile: "还没有可用的模型配置，去设置里添加一个",
  sessionGone: "这个会话已在别处删除，已切到新会话",
  noModel: "选择模型",
  noKey: "无 Key",
  visionShort: "看图",
  models: "模型",
  addModel: "添加",
  modelPlaceholder: "模型名，或先获取列表",
  noOutput: "当前页面还没有出图",
  tooManyImages: "每条消息最多 4 张图",
  imageTooLarge: "图片超过 10 MB",
  attachmentMissing: "附图已丢失",
  saveFailed: "保存消息失败",
  imageOnlyTitle: "图片",
  importReport: (imported: number, skipped: number) => `已从旧版导入 ${imported} 个模型配置${skipped ? `，跳过 ${skipped} 个不支持的配置` : ""}`,
  // settings
  profiles: "模型配置",
  addProfile: "添加配置",
  profileName: "名称",
  baseUrl: "Base URL",
  model: "模型",
  apiKey: "API Key",
  apiKeySaved: "已保存（留空不修改）",
  apiKeyClear: "清除已保存的 Key",
  reasoning: "推理强度",
  reasoningDefault: "默认",
  memory: "记忆",
  memoryHint: "MEMORY.md：agent 记下的本地设置与偏好，每轮都会发给模型。可以直接改，也可以让 agent 记住或忘掉。",
  memoryEmpty: "# 本地模型\n- 最新的多合一 LoRA：…",
  memoryReload: "重新读取",
  reasoningReset: "恢复默认",
  reasoningFast: "速度更快",
  reasoningSmart: "更智能",
  reasoningRecommended: "推荐",
  reasoningHelp: "更高的推理强度让模型思考更久、回答更周全，但更慢。默认即使用服务商设置。可用档位取决于模型，不支持的档位会报错。",
  vision: "支持看图（视觉）",
  temperature: "温度（可空）",
  maxTokens: "最大输出长度（可空）",
  fetchModels: "获取模型列表",
  setDefault: "设为默认",
  isDefault: "默认",
  civitai: "Civitai",
  civitaiEnabled: "允许联网查询 Civitai 模型信息（只发送模型哈希）",
  civitaiKey: "Civitai API Key（可选）",
  saved: "已保存",
  confirmDeleteProfile: "删除这个模型配置和它的 API Key？",
};

export const toolLabel = (name: string, labels: Record<string, string>) => labels[name] ?? name;
